config/routes.rb
Rails.application.routes.draw do
  resources :applicants
  resources :vacancies
  resources :companies
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  belongs_to :vacancy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :vacancies
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  belongs_to :company
  has_many :applicants
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :set_applicant, only: %i[ show edit update destroy ]

  # GET /applicants or /applicants.json
  def index
    @applicants = Applicant.all
  end

  # GET /applicants/1 or /applicants/1.json
  def show
  end

  # GET /applicants/new
  def new
    @applicant = Applicant.new
  end

  # GET /applicants/1/edit
  def edit
  end

  # POST /applicants or /applicants.json
  def create
    @applicant = Applicant.new(applicant_params)

    respond_to do |format|
      if @applicant.save
        format.html { redirect_to applicant_url(@applicant), notice: "Applicant was successfully created." }
        format.json { render :show, status: :created, location: @applicant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicants/1 or /applicants/1.json
  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html { redirect_to applicant_url(@applicant), notice: "Applicant was successfully updated." }
        format.json { render :show, status: :ok, location: @applicant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicants/1 or /applicants/1.json
  def destroy
    @applicant.destroy

    respond_to do |format|
      format.html { redirect_to applicants_url, notice: "Applicant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant
      @applicant = Applicant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def applicant_params
      params.require(:applicant).permit(:name, :vacancy_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /companies or /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to company_url(@company), notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to company_url(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :description)
    end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :set_vacancy, only: %i[ show edit update destroy ]

  # GET /vacancies or /vacancies.json
  def index
    @vacancies = Vacancy.all
  end

  # GET /vacancies/1 or /vacancies/1.json
  def show
  end

  # GET /vacancies/new
  def new
    @vacancy = Vacancy.new
  end

  # GET /vacancies/1/edit
  def edit
  end

  # POST /vacancies or /vacancies.json
  def create
    @vacancy = Vacancy.new(vacancy_params)

    respond_to do |format|
      if @vacancy.save
        format.html { redirect_to vacancy_url(@vacancy), notice: "Vacancy was successfully created." }
        format.json { render :show, status: :created, location: @vacancy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacancies/1 or /vacancies/1.json
  def update
    respond_to do |format|
      if @vacancy.update(vacancy_params)
        format.html { redirect_to vacancy_url(@vacancy), notice: "Vacancy was successfully updated." }
        format.json { render :show, status: :ok, location: @vacancy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacancies/1 or /vacancies/1.json
  def destroy
    @vacancy.destroy

    respond_to do |format|
      format.html { redirect_to vacancies_url, notice: "Vacancy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacancy
      @vacancy = Vacancy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vacancy_params
      params.require(:vacancy).permit(:title, :location, :description, :requirements, :salary, :availabre, :company_id)
    end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/applicants/_applicant.html.erb
<div id="<%= dom_id applicant %>">
  <p>
    <strong>Name:</strong>
    <%= applicant.name %>
  </p>

  <p>
    <strong>Vacancy:</strong>
    <%= applicant.vacancy_id %>
  </p>

</div>

app/views/applicants/_form.html.erb
<%= form_with(model: applicant) do |form| %>
  <% if applicant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(applicant.errors.count, "error") %> prohibited this applicant from being saved:</h2>

      <ul>
        <% applicant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :vacancy_id, style: "display: block" %>
    <%= form.text_field :vacancy_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/applicants/edit.html.erb
<h1>Editing applicant</h1>

<%= render "form", applicant: @applicant %>

<br>

<div>
  <%= link_to "Show this applicant", @applicant %> |
  <%= link_to "Back to applicants", applicants_path %>
</div>

app/views/applicants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Applicants</h1>

<div id="applicants">
  <% @applicants.each do |applicant| %>
    <%= render applicant %>
    <p>
      <%= link_to "Show this applicant", applicant %>
    </p>
  <% end %>
</div>

<%= link_to "New applicant", new_applicant_path %>

app/views/applicants/new.html.erb
<h1>New applicant</h1>

<%= render "form", applicant: @applicant %>

<br>

<div>
  <%= link_to "Back to applicants", applicants_path %>
</div>

app/views/applicants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @applicant %>

<div>
  <%= link_to "Edit this applicant", edit_applicant_path(@applicant) %> |
  <%= link_to "Back to applicants", applicants_path %>

  <%= button_to "Destroy this applicant", @applicant, method: :delete %>
</div>

app/views/companies/_company.html.erb
<div id="<%= dom_id company %>">
  <p>
    <strong>Name:</strong>
    <%= company.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= company.description %>
  </p>

</div>

app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
  <% if company.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Show this company", @company %> |
  <%= link_to "Back to companies", companies_path %>
</div>

app/views/companies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Companies</h1>

<div id="companies">
  <% @companies.each do |company| %>
    <%= render company %>
    <p>
      <%= link_to "Show this company", company %>
    </p>
  <% end %>
</div>

<%= link_to "New company", new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Back to companies", companies_path %>
</div>

app/views/companies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @company %>

<div>
  <%= link_to "Edit this company", edit_company_path(@company) %> |
  <%= link_to "Back to companies", companies_path %>

  <%= button_to "Destroy this company", @company, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tomatefreelas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vacancies/_form.html.erb
<%= form_with(model: vacancy) do |form| %>
  <% if vacancy.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vacancy.errors.count, "error") %> prohibited this vacancy from being saved:</h2>

      <ul>
        <% vacancy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :requirements, style: "display: block" %>
    <%= form.text_field :requirements %>
  </div>

  <div>
    <%= form.label :salary, style: "display: block" %>
    <%= form.text_field :salary %>
  </div>

  <div>
    <%= form.label :availabre, style: "display: block" %>
    <%= form.check_box :availabre %>
  </div>

  <div>
    <%= form.label :company_id, style: "display: block" %>
    <%= form.text_field :company_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vacancies/_vacancy.html.erb
<div id="<%= dom_id vacancy %>">
  <p>
    <strong>Title:</strong>
    <%= vacancy.title %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= vacancy.location %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= vacancy.description %>
  </p>

  <p>
    <strong>Requirements:</strong>
    <%= vacancy.requirements %>
  </p>

  <p>
    <strong>Salary:</strong>
    <%= vacancy.salary %>
  </p>

  <p>
    <strong>Availabre:</strong>
    <%= vacancy.availabre %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= vacancy.company_id %>
  </p>

</div>

app/views/vacancies/edit.html.erb
<h1>Editing vacancy</h1>

<%= render "form", vacancy: @vacancy %>

<br>

<div>
  <%= link_to "Show this vacancy", @vacancy %> |
  <%= link_to "Back to vacancies", vacancies_path %>
</div>

app/views/vacancies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Vacancies</h1>

<div id="vacancies">
  <% @vacancies.each do |vacancy| %>
    <%= render vacancy %>
    <p>
      <%= link_to "Show this vacancy", vacancy %>
    </p>
  <% end %>
</div>

<%= link_to "New vacancy", new_vacancy_path %>

app/views/vacancies/new.html.erb
<h1>New vacancy</h1>

<%= render "form", vacancy: @vacancy %>

<br>

<div>
  <%= link_to "Back to vacancies", vacancies_path %>
</div>

app/views/vacancies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vacancy %>

<div>
  <%= link_to "Edit this vacancy", edit_vacancy_path(@vacancy) %> |
  <%= link_to "Back to vacancies", vacancies_path %>

  <%= button_to "Destroy this vacancy", @vacancy, method: :delete %>
</div>